site_name: Kudos Docs
site_description: Enterprise productivity solutions
site_author: Andrew Reynolds
site_url: https://docs.kudosapps.com
repo_url: https://www.kudosapps.com
repo_name: kudosapps.com

extra:
  social:
    - type: "github"
      link: "https://github.com/isw-kudos"
    - type: "twitter"
      link: "https://twitter.com/kudosbadges"
    - type: "linkedin"
      link: "https://www.linkedin.com/company/isw_2/about/"
    - type: "youtube"
      link: "https://www.youtube.com/channel/UC_9nMUcp6jcweQZML2qIy8A"
nav:
  - Welcome: index.md
  - Kudos Analytics:
    - Installation:
      - FAQ: analytics/websphere-faq.md
  - Kudos Badges:
    - Installation:
      - FAQ: badges/websphere-faq.md
  - Kudos Boards:
      - Overview: boards/index.md
      - Installation:
        - IBM ICP (Kubernetes): boards/icp.md
        - Docker Swarm: boards/swarm.md
        - Websphere: boards/websphere.md
        - WAS Config: boards/wasconfig.md
        - Connections Widgets: boards/widgets.md
        - FAQ: boards/websphere-faq.md
  - Kudos Ideas:
      - Overview: ideas/index.md
      - Connections Cloud: ideas/cloud-setup.md
  - Buzzy:
      - Overview: buzzy/index.md
      - Installation:
          - IBM ICP (Kubernetes): buzzy/buzzy-icp.md
          - WAS Config: buzzy/buzzy-wasconfig.md
          - Connections Widgets: buzzy/buzzy-widgets.md
  - Docker Swarm: swarm/setup.md

markdown_extensions:
  - toc:
      permalink: true

theme:
  name: material
  palette:
    primary: orange
    accent: light blue
  favicon: assets/images/favicon.ico
  logo:
    icon: local_library

extra_css:
  - "assets/css/custom.css"

google_analytics:
  - "UA-1747668-5"
  - "auto"
